# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4249571cec18c46d650287c24068afcdb60f995caf601b1cbea69e23793d1e383b90dfe27d1d7c6c1d63e1748e76f778afea1159e4d3a2228c4e5b6edb808e8f

test:
  secret_key_base: 1a61a954fda884008f0634d93a039f506d33a5d2b5023e5cb197b5abead7e63b3a9731f4fe78d5bad453bac7677d9cd8c624d3dea5fa9f6266bcf0ca46ac62f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
